void printaMenu();
void printaMenu2();
void printaMenu3();
int lerArquivo(char *nome_arquivo, double *numeros, int TAMANHO_MAXIMO);
void bubbleSort(int tamanho, double *vetor);
void insertSort(int tamanho, double *vetor);
void selectionSort(int tamanho, double *vetor);
void gerarCrescente(int tam);
void gerarDecrescente(int tam);
void gerarAleatorio(int tam, int max);